### ISSUE TITLE
Add Cortana like Visualizations for Susi on Magic Mirror

### ISSUE THREAD

**Issue by betterclever** [fossasia/MMM-SUSI-AI#9]
We should add Cortana like Full Screen mode (Cortana on Windows 10) with visualization on the Susi Magic Mirror module. 

![screenshot 9](https://user-images.githubusercontent.com/16309034/27808464-9ef1a4da-6065-11e7-9a75-33ac6c240262.png)

I am working on this.

**Comment by mariobehling** [comment]
Please don't do this. SUSI should be a widget. Why should all the data not be visible anymore. Just use one part of the screen. 

Closing this issue.
